const T={
 it:{heroTitle:'Il vero sapore di Napoli a Las Galletas',heroText:'Rosticceria napoletana artigianale: pizza, fritti, primi piatti e specialità preparate ogni giorno con passione.',btnMenu:'Scopri il menù',btnMap:'Come arrivare',introTitle:'Fatto a mano, come a Napoli.',introText:'Da El Capricho trovi prodotti preparati ogni giorno: impasti, ripieni, fritti, piatti al forno e sapori della tradizione. Un angolo di Napoli nel cuore di Tenerife.',specTitle:'Le nostre specialità',menuNote:'Il menù può cambiare secondo la disponibilità del giorno. Chiamaci per informazioni.',buffetTitle:'Buffet napoletani',buffetText:'Prepariamo buffet per compleanni, feste, riunioni e occasioni speciali: pizza, fritti, panini, piatti al forno e dolci.',btnCall:'Chiama ora',galleryTitle:'Dentro El Capricho',hours:'Orari aggiornati su Google.'},
 es:{heroTitle:'El auténtico sabor de Nápoles en Las Galletas',heroText:'Rosticcería napolitana artesanal: pizza, fritos, primeros platos y especialidades preparadas cada día con pasión.',btnMenu:'Ver el menú',btnMap:'Cómo llegar',introTitle:'Hecho a mano, como en Nápoles.',introText:'En El Capricho encontrarás productos preparados cada día: masas, rellenos, fritos, platos al horno y sabores de la tradición napolitana.',specTitle:'Nuestras especialidades',menuNote:'El menú puede cambiar según la disponibilidad del día. Llámanos para más información.',buffetTitle:'Buffets napolitanos',buffetText:'Preparamos buffets para cumpleaños, fiestas, reuniones y ocasiones especiales: pizza, fritos, bocadillos, platos al horno y postres.',btnCall:'Llamar ahora',galleryTitle:'Dentro de El Capricho',hours:'Horarios actualizados en Google.'},
 en:{heroTitle:'The true taste of Naples in Las Galletas',heroText:'Artisanal Neapolitan rosticceria: pizza, fried specialties, pasta dishes and daily homemade recipes.',btnMenu:'See the menu',btnMap:'Get directions',introTitle:'Handmade, like in Naples.',introText:'At El Capricho you will find products prepared every day: doughs, fillings, fried specialties, baked dishes and traditional Neapolitan flavours.',specTitle:'Our specialties',menuNote:'The menu may change depending on daily availability. Call us for details.',buffetTitle:'Neapolitan buffets',buffetText:'We prepare buffets for birthdays, parties, meetings and special occasions: pizza, fried specialties, sandwiches, baked dishes and desserts.',btnCall:'Call now',galleryTitle:'Inside El Capricho',hours:'Opening hours updated on Google.'}
};
function setLang(lang){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=T[lang][el.dataset.i18n]||el.textContent);document.querySelectorAll('.langs button').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));localStorage.setItem('lang',lang)}
document.querySelectorAll('.langs button').forEach(b=>b.onclick=()=>setLang(b.dataset.lang));
const grid=document.getElementById('menuGrid'),filters=document.getElementById('filters');
const cats=['Tutto',...new Set(window.MENU.map(i=>i.category))];
function render(cat='Tutto'){grid.innerHTML='';window.MENU.filter(i=>cat==='Tutto'||i.category===cat).forEach(i=>{let c=document.createElement('article');c.className='menu-card reveal in';c.innerHTML=`<img src="${i.img}" alt="${i.name}"><div><h3>${i.name}</h3><p>${i.desc}</p></div>`;grid.appendChild(c)});document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.textContent===cat))}
cats.forEach(c=>{let b=document.createElement('button');b.className='filter';b.textContent=c;b.onclick=()=>render(c);filters.appendChild(b)});render();setLang(localStorage.getItem('lang')||'it');
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>obs.observe(el));
