const PHONE='34666196026';
const products={
pizza:[
 ['Pizza Margherita','Pomodoro, mozzarella, pomodorini e basilico.','pizza-margherita.jpg'],
 ['Pizza Marinara','Pomodoro, aglio, origano e olio extravergine.','pizza-marinara.jpg'],
 ['Pizza Diavola','Pomodoro, mozzarella e salame piccante.','pizza-diavola.jpg'],
 ['Salsiccia e friarielli','Salsiccia napoletana, friarielli e mozzarella.','pizza-salsiccia-friarielli.jpg'],
 ['Salsiccia, peperoni e mozzarella','Una pizza ricca, colorata e saporita.','pizza-salsiccia-peperoni.jpg'],
 ['Pizza Ortolana','Melanzane, zucchine, pomodorini e mozzarella.','pizza-ortolana.jpg'],
 ['Panna, prosciutto cotto e mais','Cremosa e delicata, cotta in teglia.','pizza-panna-cotto-mais.jpg'],
 ['Parigina','Pizza ripiena con pomodoro, prosciutto cotto, mozzarella e sfoglia.','parigina.jpg']
],
fritti:[
 ['Frittatina di pasta','Pasta, besciamella, carne, piselli e panatura croccante.','frittatina-aperta.jpg'],
 ['Crocchè di patate','Crocchè dorati e croccanti, preparati secondo tradizione.','crocche.jpg'],
 ['Mozzarella in carrozza','Pane, mozzarella e panatura dorata.','mozzarella-carrozza.jpg'],
 ['Pizza fritta','Impasto soffice, fritto al momento.','pizza-fritta.jpg'],
 ['Fritti misti','Una selezione delle nostre specialità napoletane.','fritti-misti.jpg']
],
cucina:[
 ['Pasta al forno napoletana','Pasta al forno ricca, filante e piena di sapore.','pasta-forno.jpg'],
 ['Parmigiana di melanzane','Melanzane, pomodoro, mozzarella, basilico e parmigiano.','parmigiana.jpg'],
 ['Polpette al ragù','Polpette morbide cotte lentamente nel ragù.','polpette-ragu.jpg'],
 ['Panino con cotoletta','Cotoletta di pollo, insalata e pomodoro.','panino-cotoletta.jpg']
],
tradizione:[
 ['Pane cafone napoletano','Pane artigianale dalla crosta fragrante.','pane-cafone.jpg'],
 ['Casatiello napoletano','Una delle specialità più amate della tradizione.','casatiello.jpg'],
 ['La nostra vetrina','Produzione artigianale e varietà ogni giorno.','hero.jpg']
]};
const translations={
it:{navMenu:'Menù',navStory:'Chi siamo',navContact:'Contatti',heroEyebrow:'Autentica tradizione napoletana',heroTitle:'Il vero sapore di Napoli a Las Galletas',heroText:'Pizza, fritti, pane e piatti preparati ogni giorno con passione.',discover:'Scopri le specialità',buffetOrder:'Ordina un buffet',call:'Chiama ora',events:'Feste ed eventi',customBuffet:'Buffet personalizzati',ourIdentity:'La nostra identità',introTitle:'Napoli, ogni giorno, nella nostra vetrina',introText:'Una rosticceria autentica dove pizza, fritti, cucina e pane raccontano la tradizione con ingredienti selezionati e lavorazione artigianale.',freshTitle:'Preparato ogni giorno',freshText:'Produzione fresca, dal forno alla vetrina.',tradTitle:'Ricette autentiche',tradText:'Sapori e specialità della cucina napoletana.',buffetTitle:'Buffet su misura',buffetText:'Soluzioni per compleanni, feste e aziende.',menuEyebrow:'La vetrina di El Capricho',menuTitle:'Le nostre specialità',menuText:'Seleziona una categoria e scopri una parte della nostra produzione.',pizzas:'Pizze',fried:'Fritti',kitchen:'Cucina',tradition:'Tradizione',availability:'La disponibilità può cambiare durante la giornata: chiedici cosa trovi oggi in vetrina.',houseSpecialty:'Specialità della casa',breadTitle:'Crosta fragrante, mollica soffice, profumo di casa',breadText:'Il nostro pane artigianale merita uno spazio tutto suo. Preparato secondo la tradizione e disponibile fino a esaurimento.',reserveBread:'Prenota il pane',buffetEyebrow:'Buffet ed eventi',buffetHeading:'Portiamo El Capricho alla tua festa',buffetIntro:'Prepariamo buffet su ordinazione per compleanni, riunioni, feste private ed eventi aziendali. Scegli il numero di persone e raccontaci cosa desideri.',buffetOne:'Fritti e rosticceria napoletana',buffetTwo:'Pizza, panini e specialità da forno',buffetThree:'Composizioni personalizzate',buffetFour:'Ritiro concordato in negozio',buffetCtaTitle:'Richiedi il tuo buffet',buffetCtaText:'Compila i dati: si aprirà un messaggio pronto da inviare.',name:'Nome',phone:'Telefono',date:'Data evento',people:'Numero persone',eventType:'Tipo di evento',request:'Cosa vorresti nel buffet?',sendWhatsapp:'Invia richiesta su WhatsApp',contactEyebrow:'Vieni a trovarci',callUs:'Chiamaci',directions:'Indicazioni',hoursNote:'Per orari e disponibilità giornaliera, contattaci direttamente.',floatingBuffet:'Ordina buffet',waNote:'WhatsApp +34 666 196 026 è riservato alle richieste buffet. Non si accettano ordini giornalieri tramite WhatsApp.'},
es:{navMenu:'Menú',navStory:'Quiénes somos',navContact:'Contacto',heroEyebrow:'Auténtica tradición napolitana',heroTitle:'El verdadero sabor de Nápoles en Las Galletas',heroText:'Pizza, fritos, pan y platos preparados cada día con pasión.',discover:'Descubre las especialidades',buffetOrder:'Encarga un buffet',call:'Llama ahora',events:'Fiestas y eventos',customBuffet:'Buffets personalizados',ourIdentity:'Nuestra identidad',introTitle:'Nápoles, cada día, en nuestro mostrador',introText:'Una rosticería auténtica donde pizza, fritos, cocina y pan cuentan la tradición con ingredientes seleccionados y elaboración artesanal.',freshTitle:'Preparado cada día',freshText:'Producción fresca, del horno al mostrador.',tradTitle:'Recetas auténticas',tradText:'Sabores y especialidades de la cocina napolitana.',buffetTitle:'Buffet a medida',buffetText:'Soluciones para cumpleaños, fiestas y empresas.',menuEyebrow:'El mostrador de El Capricho',menuTitle:'Nuestras especialidades',menuText:'Selecciona una categoría y descubre parte de nuestra producción.',pizzas:'Pizzas',fried:'Fritos',kitchen:'Cocina',tradition:'Tradición',availability:'La disponibilidad puede cambiar durante el día: pregúntanos qué hay hoy.',houseSpecialty:'Especialidad de la casa',breadTitle:'Corteza crujiente, miga suave, aroma de hogar',breadText:'Nuestro pan artesanal merece un espacio propio. Preparado según la tradición y disponible hasta agotar existencias.',reserveBread:'Reserva el pan',buffetEyebrow:'Buffets y eventos',buffetHeading:'Llevamos El Capricho a tu fiesta',buffetIntro:'Preparamos buffets por encargo para cumpleaños, reuniones, fiestas privadas y eventos de empresa.',buffetOne:'Fritos y rosticería napolitana',buffetTwo:'Pizza, bocadillos y especialidades al horno',buffetThree:'Composiciones personalizadas',buffetFour:'Recogida acordada en el local',buffetCtaTitle:'Solicita tu buffet',buffetCtaText:'Completa los datos y se abrirá un mensaje listo para enviar.',name:'Nombre',phone:'Teléfono',date:'Fecha del evento',people:'Número de personas',eventType:'Tipo de evento',request:'¿Qué deseas en el buffet?',sendWhatsapp:'Enviar solicitud por WhatsApp',contactEyebrow:'Ven a visitarnos',callUs:'Llámanos',directions:'Cómo llegar',hoursNote:'Para horarios y disponibilidad diaria, contáctanos directamente.',floatingBuffet:'Pedir buffet',waNote:'WhatsApp +34 666 196 026 está reservado para solicitudes de buffet. No se aceptan pedidos diarios por WhatsApp.'},
en:{navMenu:'Menu',navStory:'About us',navContact:'Contact',heroEyebrow:'Authentic Neapolitan tradition',heroTitle:'The true taste of Naples in Las Galletas',heroText:'Pizza, fried specialties, bread and dishes made fresh every day.',discover:'Discover our specialties',buffetOrder:'Order a buffet',call:'Call now',events:'Parties and events',customBuffet:'Custom buffets',ourIdentity:'Our identity',introTitle:'Naples, every day, in our counter',introText:'An authentic rosticceria where pizza, fried food, cooking and bread tell the story of Neapolitan tradition.',freshTitle:'Made every day',freshText:'Fresh production, straight from the oven.',tradTitle:'Authentic recipes',tradText:'Flavours and specialties from Neapolitan cuisine.',buffetTitle:'Tailored buffets',buffetText:'Solutions for birthdays, parties and companies.',menuEyebrow:'El Capricho counter',menuTitle:'Our specialties',menuText:'Select a category and discover part of our daily production.',pizzas:'Pizza',fried:'Fried',kitchen:'Kitchen',tradition:'Tradition',availability:'Availability may change during the day: ask us what is in the counter today.',houseSpecialty:'House specialty',breadTitle:'Crisp crust, soft crumb, the aroma of home',breadText:'Our artisan bread deserves a space of its own. Made following tradition and available while supplies last.',reserveBread:'Reserve bread',buffetEyebrow:'Buffets and events',buffetHeading:'Bring El Capricho to your party',buffetIntro:'We prepare made-to-order buffets for birthdays, meetings, private parties and corporate events.',buffetOne:'Neapolitan fried specialties',buffetTwo:'Pizza, sandwiches and baked specialties',buffetThree:'Custom selections',buffetFour:'Collection arranged at the shop',buffetCtaTitle:'Request your buffet',buffetCtaText:'Complete the details and a ready-to-send message will open.',name:'Name',phone:'Phone',date:'Event date',people:'Number of guests',eventType:'Event type',request:'What would you like in the buffet?',sendWhatsapp:'Send request on WhatsApp',contactEyebrow:'Visit us',callUs:'Call us',directions:'Directions',hoursNote:'For opening hours and daily availability, contact us directly.',floatingBuffet:'Order buffet',waNote:'WhatsApp +34 666 196 026 is reserved for buffet enquiries. Daily food orders are not accepted on WhatsApp.'}};
let lang='it';
function render(cat='pizza'){const grid=document.querySelector('#productGrid');grid.innerHTML=products[cat].map(([n,d,i])=>`<article class="product-card"><img loading="lazy" src="assets/${i}" alt="${n}"><div class="copy"><h3>${n}</h3><p>${d}</p></div></article>`).join('')}
render();
document.querySelectorAll('.tabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)}));
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('.nav');toggle.addEventListener('click',()=>{nav.classList.toggle('open');toggle.setAttribute('aria-expanded',nav.classList.contains('open'))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
document.querySelectorAll('.langs button').forEach(b=>b.addEventListener('click',()=>{lang=b.dataset.lang;document.querySelectorAll('.langs button').forEach(x=>x.classList.toggle('active',x===b));document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(translations[lang][k])el.textContent=translations[lang][k]})}));
document.querySelector('#buffetForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const intro={it:'Ciao El Capricho! Vorrei informazioni per un buffet.',es:'¡Hola El Capricho! Quisiera información para un buffet.',en:'Hello El Capricho! I would like information about a buffet.'}[lang];const labels={it:['Nome','Telefono','Data','Persone','Evento','Richiesta'],es:['Nombre','Teléfono','Fecha','Personas','Evento','Solicitud'],en:['Name','Phone','Date','Guests','Event','Request']}[lang];const values=[f.get('name'),f.get('phone'),f.get('date'),f.get('people'),f.get('event'),f.get('details')];const msg=intro+'\n\n'+labels.map((label,i)=>`${label}: ${values[i]}`).join('\n');window.open(`https://wa.me/${PHONE}?text=${encodeURIComponent(msg)}`,'_blank')});
document.querySelector('.wa-bread').addEventListener('click',e=>{e.preventDefault();window.location.href='tel:+34922731223'});
const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
